# Generated by Django 3.0.2 on 2020-11-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('font', models.CharField(max_length=200)),
                ('fontSize', models.IntegerField(max_length=10)),
                ('color', models.CharField(max_length=200)),
            ],
        ),
    ]
